-- Territorial inputs are intentionally not duplicated in SQL seed statements.
--
-- Authoritative, versioned input files:
--   data/model_inputs/*.csv
--
-- Load them after schema initialization with:
--   python scripts/load_model_inputs.py
--
-- This preserves a single reproducible source for the 25 model territories and
-- avoids presenting the values as externally verified observations.
